USE SCHOOL
SELECT DISTINCT STUDENTS.SID, SNAME
FROM STUDENTS, CHOICES, COURSES
WHERE STUDENTS.SID = CHOICES.SID
AND CHOICES.CID = COURSES.CID
AND CNAME = 'C++'
AND SCORE > (SELECT SCORE
            FROM STUDENTS, CHOICES, COURSES
            WHERE STUDENTS.SID = CHOICES.SID
            AND CHOICES.CID = COURSES.CID
            AND CNAME = 'C++'
            AND SNAME = 'ZNKOO')