USE SCHOOL
SELECT DISTINCT CNAME
FROM CHOICES, COURSES
WHERE CHOICES.CID = COURSES.CID
AND CHOICES.TID IN (SELECT TID
                    FROM CHOICES, COURSES
                    WHERE CHOICES.CID = COURSES.CID AND COURSES.CNAME = 'UML')