set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN U18 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports {aluCtr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aluCtr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aluCtr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aluCtr[0]}]
set_property PACKAGE_PIN R2 [get_ports {aluCtr[3]}]
set_property PACKAGE_PIN T1 [get_ports {aluCtr[2]}]
set_property PACKAGE_PIN U1 [get_ports {aluCtr[1]}]
set_property PACKAGE_PIN W2 [get_ports {aluCtr[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {input3[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input3[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input3[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input3[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input3[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input3[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input3[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input3[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {input3[0]}]
set_property PACKAGE_PIN V2 [get_ports {input3[8]}]
set_property PACKAGE_PIN W13 [get_ports {input3[7]}]
set_property PACKAGE_PIN W14 [get_ports {input3[6]}]
set_property PACKAGE_PIN V15 [get_ports {input3[5]}]
set_property PACKAGE_PIN W15 [get_ports {input3[4]}]
set_property PACKAGE_PIN W17 [get_ports {input3[3]}]
set_property PACKAGE_PIN W16 [get_ports {input3[2]}]
set_property PACKAGE_PIN V16 [get_ports {input3[1]}]
set_property PACKAGE_PIN V17 [get_ports {input3[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[0]}]
set_property PACKAGE_PIN U2 [get_ports {sm_wei[0]}]
set_property PACKAGE_PIN U4 [get_ports {sm_wei[1]}]
set_property PACKAGE_PIN V4 [get_ports {sm_wei[2]}]
set_property PACKAGE_PIN W4 [get_ports {sm_wei[3]}]