# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/guzy0/CPU/CPU.cache/wt [current_project]
set_property parent.project_path C:/Users/guzy0/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom.xci
set_property used_in_implementation false [get_files -all c:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom.dcp]
set_property is_locked true [get_files C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom.xci]

synth_design -top irom -part xc7a35tcpg236-1 -mode out_of_context
rename_ref -prefix_all irom_
write_checkpoint -noxdef irom.dcp
catch { report_utilization -file irom_utilization_synth.rpt -pb irom_utilization_synth.pb }
if { [catch {
  file copy -force C:/Users/guzy0/CPU/CPU.runs/irom_synth_1/irom.dcp C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Users/guzy0/CPU/CPU.ip_user_files/ip/irom]} {
  catch { 
    file copy -force C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom_stub.v C:/Users/guzy0/CPU/CPU.ip_user_files/ip/irom
  }
}

if {[file isdir C:/Users/guzy0/CPU/CPU.ip_user_files/ip/irom]} {
  catch { 
    file copy -force C:/Users/guzy0/CPU/CPU.srcs/sources_1/ip/irom/irom_stub.vhdl C:/Users/guzy0/CPU/CPU.ip_user_files/ip/irom
  }
}
