# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/guzy0/rom/rom.cache/wt [current_project]
set_property parent.project_path C:/Users/guzy0/rom/rom.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{C:/Users/guzy0/rom/New Folder/prgmip16.coe}}
add_files {{c:/Users/guzy0/rom/New Folder/prgmip8.coe}}
add_files -quiet C:/Users/guzy0/rom/rom.runs/Ins_Rom_synth_1/Ins_Rom.dcp
set_property used_in_implementation false [get_files C:/Users/guzy0/rom/rom.runs/Ins_Rom_synth_1/Ins_Rom.dcp]
add_files -quiet C:/Users/guzy0/rom/rom.runs/Ins_Rom_2_synth_1/Ins_Rom_2.dcp
set_property used_in_implementation false [get_files C:/Users/guzy0/rom/rom.runs/Ins_Rom_2_synth_1/Ins_Rom_2.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/guzy0/rom/rom.srcs/sources_1/new/display.v
  C:/Users/guzy0/rom/rom.srcs/sources_1/new/rom_top.v
}
read_xdc C:/Users/guzy0/rom/rom.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files C:/Users/guzy0/rom/rom.srcs/constrs_1/new/constraint.xdc]

synth_design -top rom_top -part xc7a35tcpg236-1
write_checkpoint -noxdef rom_top.dcp
catch { report_utilization -file rom_top_utilization_synth.rpt -pb rom_top_utilization_synth.pb }
