# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/guzy0/pipeline/pipeline.srcs/sources_1/ip/InstructionROM/InstructionROM.xci
# IP: The module: 'InstructionROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/guzy0/pipeline/pipeline.srcs/sources_1/ip/InstructionROM/InstructionROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstructionROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/guzy0/pipeline/pipeline.srcs/sources_1/ip/InstructionROM/InstructionROM.xci
# IP: The module: 'InstructionROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/guzy0/pipeline/pipeline.srcs/sources_1/ip/InstructionROM/InstructionROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstructionROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
