# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/guzy0/ALU/ALU.cache/wt [current_project]
set_property parent.project_path C:/Users/guzy0/ALU/ALU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/guzy0/calculator/calculator.srcs/sources_1/new [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/guzy0/ALU/ALU.srcs/sources_1/new/display.v
  C:/Users/guzy0/ALU/ALU.srcs/sources_1/new/alu.v
  C:/Users/guzy0/ALU/ALU.srcs/sources_1/new/top.v
}
read_xdc C:/Users/guzy0/ALU/ALU.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/guzy0/ALU/ALU.srcs/constrs_1/new/cons.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
