# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/project/8b_pri_carry/8b_pri_carry.cache/wt [current_project]
set_property parent.project_path G:/project/8b_pri_carry/8b_pri_carry.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib G:/project/8b_pri_carry/8b_pri_carry.srcs/sources_1/new/add_8.v
synth_design -top add_8 -part xc7vx485tffg1157-1
write_checkpoint -noxdef add_8.dcp
catch { report_utilization -file add_8_utilization_synth.rpt -pb add_8_utilization_synth.pb }
