# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design_1.xdc

# Block Designs: bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/design_1/ip/design_1_sysu_74LS283_0_0/design_1_sysu_74LS283_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sysu_74LS283_0_0 || ORIG_REF_NAME==design_1_sysu_74LS283_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sysu_74LS86_0_0/design_1_sysu_74LS86_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sysu_74LS86_0_0 || ORIG_REF_NAME==design_1_sysu_74LS86_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sysu_74LS32_0_0/design_1_sysu_74LS32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sysu_74LS32_0_0 || ORIG_REF_NAME==design_1_sysu_74LS32_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sysu_74LS08_0_0/design_1_sysu_74LS08_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sysu_74LS08_0_0 || ORIG_REF_NAME==design_1_sysu_74LS08_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sysu_74LS04_0_0/design_1_sysu_74LS04_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sysu_74LS04_0_0 || ORIG_REF_NAME==design_1_sysu_74LS04_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sysu_high_level_0_1/design_1_sysu_high_level_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sysu_high_level_0_1 || ORIG_REF_NAME==design_1_sysu_high_level_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sysu_low_level_0_1/design_1_sysu_low_level_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sysu_low_level_0_1 || ORIG_REF_NAME==design_1_sysu_low_level_0_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
