--create_table.sql
USE MY_TEST
CREATE TABLE CUSTOMERS
(
    CID CHAR(8) NOT NULL UNIQUE,
    CNAME CHAR(20) NOT NULL,
    CITY CHAR(20) NOT NULL,
    DISCNT CHAR(20) NOT NULL,
    PRIMARY KEY(CID)
)
CREATE TABLE AGENTS
(
    AID CHAR(8) NOT NULL UNIQUE,
    ANAME CHAR(20) NOT NULL,
    CITY CHAR(20) NOT NULL,
    PERCEN CHAR(20) NOT NULL,
    PRIMARY KEY(AID)
)
CREATE TABLE PRODUCTS
(
    PID CHAR(8) NOT NULL UNIQUE,
    PNAME CHAR(20) NOT NULL
        PRIMARY KEY(PID)
)
CREATE TABLE ORDERS
(
    ORDNA CHAR(8) NOT NULL UNIQUE,
    MONTH CHAR(8) NOT NULL,
    CID CHAR(8) NOT NULL UNIQUE,
    AID CHAR(8) NOT NULL UNIQUE,
    PID CHAR(8) NOT NULL UNIQUE,
    QTY CHAR(8) NOT NULL,
    DOLLARS CHAR(8) NOT NULL,
    PRIMARY KEY(ORDNA),
    FOREIGN KEY(CID) REFERENCES CUSTOMERS ON DELETE CASCADE,
    FOREIGN KEY(AID) REFERENCES AGENTS ON DELETE CASCADE,
    FOREIGN KEY(PID) REFERENCES PRODUCTS ON DELETE CASCADE
)